#ifndef FLASH_MEMORY_H
#define FLASH_MEMORY_H

#include <cstddef>

const static size_t FLIGHT_FLASH_PAGE_SIZE = 256;
static constexpr size_t FLIGHT_FLASH_BLOCK_SIZE = 65536;
static constexpr size_t FLIGHT_FLASH_PAGES_PER_BLOCK = FLIGHT_FLASH_BLOCK_SIZE / FLIGHT_FLASH_PAGE_SIZE;
static constexpr size_t FLIGHT_FLASH_PAGE_COUNT = (1 << 22) / FLIGHT_FLASH_PAGE_SIZE;
static constexpr size_t FLIGHT_FLASH_BLOCK_COUNT = FLIGHT_FLASH_PAGE_COUNT / FLIGHT_FLASH_PAGES_PER_BLOCK;
static constexpr size_t FLIGHT_FLASH_FLIGHTS = 1;
static constexpr size_t FLIGHT_FLASH_FLIGHT_PAGES = FLIGHT_FLASH_PAGES_PER_BLOCK * (FLIGHT_FLASH_BLOCK_COUNT / FLIGHT_FLASH_FLIGHTS);
static constexpr size_t FLIGHT_FLASH_FLIGHT_SIZE = FLIGHT_FLASH_FLIGHT_PAGES * FLIGHT_FLASH_PAGE_SIZE;

struct FlashMemory {
};

#endif
